env:
  PYTORCH_CUDA_ALLOC_CONF: expandable_segments:True

meaformer:
  model_name: MEAformer
  gpu: 0
  eval_epoch: 1
  only_test: 0
  data_choice: DBP15K
  data_split: zh_en
  data_rate: 0.3
  epoch: 1
  lr: 0.0005
  hidden_units: "128,128,128"
  save_model: 0
  batch_size: 256
  csls: true
  csls_k: 3
  random_seed: 42
  exp_name: "BYSJ_MEAformer_rtx3060"
  exp_id: "v1_zh_en_0.3_memfit"
  workers: 2
  dist: 0
  accumulation_steps: 1
  scheduler: cos
  attr_dim: 128
  img_dim: 128
  name_dim: 128
  char_dim: 128
  hidden_size: 128
  tau: 0.1
  structure_encoder: gat
  num_attention_heads: 1
  num_hidden_layers: 1
  use_surface: 0
  use_intermediate: 1
  enable_sota: false
  replay: 0
  w_img: false
  w_attr: false
